name: GitHubClient Sample

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.302
    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: '14.0.1'
    - name: Install dependencies
      run: |
        dotnet tool install --global dotnet-sonarscanner --version 4.10.0
        dotnet restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - name: Prepare Sonar scaner
      run: dotnet sonarscanner begin /k:"${{ secrets.SONAR_PROJECT_KEY }}" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" /o:"${{ secrets.SONAR_ORGANIZATION_KEY }}" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.language="cs" /d:sonar.cs.opencover.reportsPaths="./GitHubClientTest/coverage.opencover.xml" /d:sonar.exclusions="./GitHubConsoleDemo/**.**"
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Send information to Sonar host
      run: |
        export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"